# Generated by Django 6.0.4 on 2026-05-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(help_text='The main background image for the slider.', upload_to='sliders/backgrounds/')),
                ('hero_image', models.ImageField(help_text='Must be exactly 700x460 pixels.', upload_to='sliders/heroes/')),
                ('greeting_badge', models.CharField(help_text='Small badge text (Max 4 words).', max_length=50)),
                ('heading', models.CharField(help_text='Main slider heading (Max 5 words).', max_length=100)),
                ('short_description', models.TextField(help_text='Brief description (Max 20 words).', max_length=300)),
                ('button_label', models.CharField(blank=True, help_text="Text inside the button (e.g., 'Learn More').", max_length=30, null=True)),
                ('button_link', models.CharField(blank=True, help_text='Can be a full URL (https://...) or a relative path (/about/).', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this slider from the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Slider',
                'verbose_name_plural': 'Home Sliders',
                'ordering': ['-created_at'],
            },
        ),
    ]
