# Generated by Django 6.0.4 on 2026-05-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='hero_image',
            field=models.ImageField(help_text='Will be auto-cropped to 700x460 pixels and optimized under 500KB.', upload_to='sliders/heroes/'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='slider_image',
            field=models.ImageField(blank=True, help_text="Optional background image (Suggested: 1920x600px). If left blank, the theme's background color will be used.", null=True, upload_to='sliders/backgrounds/'),
        ),
    ]
