# Generated by Django 6.0.4 on 2026-05-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_homeslider_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='greeting_badge',
            field=models.CharField(help_text='Small badge text (Max 30 characters).', max_length=30),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='heading',
            field=models.CharField(help_text='Main slider heading (Max 50 characters).', max_length=50),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='short_description',
            field=models.TextField(help_text='Brief description (Max 150 characters).', max_length=150),
        ),
    ]
