# Generated by Django 6.0.4 on 2026-05-05 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_homeslider_greeting_badge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('phone_1', models.CharField(max_length=20, verbose_name='Primary Phone')),
                ('phone_2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Phone')),
                ('address', models.TextField(blank=True, null=True)),
                ('map_embed_url', models.TextField(blank=True, help_text='Google Maps embed iframe/link', null=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('description', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200, null=True)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Album',
                'ordering': ['-date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.CharField(blank=True, choices=[('layout_1', 'Layout 1 — Image with Description'), ('layout_2', 'Layout 2 — Photo Grid'), ('layout_3', 'Layout 3 — Rich Text'), ('contact', 'Contact'), ('faculty_junior', 'Faculty — Junior School'), ('faculty_middle', 'Faculty — Middle School'), ('faculty_senior', 'Faculty — Senior School'), ('gallery', 'Gallery'), ('events', 'Events'), ('notices', 'Notices'), ('students', 'Students'), ('results', 'Results'), ('admission_results', 'Admission Results')], max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('target_audience', models.CharField(choices=[('all', 'Everyone'), ('students', 'Students'), ('faculty', 'Faculty & Staff'), ('parents', 'Parents')], default='all', max_length=20)),
                ('publish_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notice',
                'ordering': ['-is_pinned', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Social Media Links',
                'verbose_name_plural': 'Social Media Links',
            },
        ),
        migrations.CreateModel(
            name='AdmissionResultUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=50)),
                ('session_year', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='uploads/admission/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Result Upload',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('school_level', models.CharField(choices=[('junior', 'Junior School'), ('middle', 'Middle School'), ('senior', 'Senior School')], max_length=10)),
                ('file', models.FileField(upload_to='uploads/faculty/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Upload',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='backend.galleryalbum')),
            ],
            options={
                'ordering': ['album', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ResultUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/results/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Result Upload',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/students/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Upload',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.CharField(choices=[('layout_1', 'Layout 1 — Image with Description'), ('layout_2', 'Layout 2 — Photo Grid'), ('layout_3', 'Layout 3 — Rich Text'), ('contact', 'Contact'), ('faculty_junior', 'Faculty — Junior School'), ('faculty_middle', 'Faculty — Middle School'), ('faculty_senior', 'Faculty — Senior School'), ('gallery', 'Gallery'), ('events', 'Events'), ('notices', 'Notices'), ('students', 'Students'), ('results', 'Results'), ('admission_results', 'Admission Results')], max_length=30)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='backend.menu')),
            ],
            options={
                'verbose_name': 'Sub Menu',
                'ordering': ['menu', 'order'],
                'unique_together': {('menu', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/sections/')),
                ('image_align', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=5)),
                ('person_name', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(blank=True, max_length=150, null=True)),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('body', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='backend.submenu')),
            ],
            options={
                'ordering': ['submenu', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PageRichText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(help_text='Raw HTML from the editor')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rich_texts', to='backend.submenu')),
            ],
            options={
                'ordering': ['submenu', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cms/photos/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='backend.submenu')),
            ],
            options={
                'ordering': ['submenu', 'order'],
            },
        ),
    ]
