# Generated by Django 5.2.8 on 2026-06-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_facility_alter_admissionresultupload_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorePillar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-lightbulb', help_text="Font Awesome class, e.g. 'fas fa-lightbulb'", max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Core Pillar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_label', models.CharField(default='Who We Are', max_length=100)),
                ('heading', models.CharField(default='A Legacy of Learning, A Future of Leaders', max_length=250)),
                ('lead_text', models.TextField(help_text='Bold introductory paragraph.')),
                ('body_text', models.TextField(help_text='Secondary paragraph below the lead.')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='home/about/')),
                ('accent_image', models.ImageField(blank=True, null=True, upload_to='home/about/')),
                ('years_of_excellence', models.PositiveSmallIntegerField(default=28)),
                ('highlight_1_icon', models.CharField(default='fas fa-medal', max_length=100)),
                ('highlight_1_title', models.CharField(default='Award-Winning Faculty', max_length=150)),
                ('highlight_1_text', models.CharField(default='Experienced, passionate educators', max_length=200)),
                ('highlight_2_icon', models.CharField(default='fas fa-globe', max_length=100)),
                ('highlight_2_title', models.CharField(default='Global Curriculum', max_length=150)),
                ('highlight_2_text', models.CharField(default='International standards, local values', max_length=200)),
                ('highlight_3_icon', models.CharField(default='fas fa-heart', max_length=100)),
                ('highlight_3_title', models.CharField(default='Holistic Development', max_length=150)),
                ('highlight_3_text', models.CharField(default='Academics, arts, sports & character', max_length=200)),
                ('button_label', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Home — About Section',
            },
        ),
        migrations.CreateModel(
            name='HomeAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(default='fas fa-trophy', help_text="Font Awesome class, e.g. 'fas fa-trophy'", max_length=100)),
                ('count', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, default='+', help_text="Text after the number, e.g. '+' or '%'", max_length=10)),
                ('label', models.CharField(max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Achievement',
                'ordering': ['order'],
            },
        ),
    ]
