# Generated by Django 5.2.8 on 2026-06-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_corepillar_homeabout_homeachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat1_count', models.PositiveIntegerField(default=3200)),
                ('stat1_suffix', models.CharField(default='+', max_length=10)),
                ('stat1_label', models.CharField(default='Students', max_length=100)),
                ('stat2_count', models.PositiveIntegerField(default=180)),
                ('stat2_suffix', models.CharField(default='+', max_length=10)),
                ('stat2_label', models.CharField(default='Faculty Members', max_length=100)),
                ('stat3_count', models.PositiveIntegerField(default=28)),
                ('stat3_suffix', models.CharField(blank=True, default='', max_length=10)),
                ('stat3_label', models.CharField(default='Years of Excellence', max_length=100)),
                ('stat4_count', models.PositiveIntegerField(default=96)),
                ('stat4_suffix', models.CharField(default='%', max_length=10)),
                ('stat4_label', models.CharField(default='Pass Rate', max_length=100)),
            ],
            options={
                'verbose_name': 'Hero Stat Bar',
            },
        ),
    ]
