# Generated by Django 5.2.8 on 2026-06-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_herostat'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Short badge label, e.g. 'Nursery & KG'", max_length=100)),
                ('age_group', models.CharField(blank=True, help_text="Age/class range, e.g. 'Ages 3–5' or 'Classes I–V · Ages 6–10'", max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='curriculum/')),
                ('icon_class', models.CharField(default='fas fa-graduation-cap', help_text='Font Awesome fallback icon when no image is uploaded (auto-assigned)', max_length=100)),
                ('heading', models.CharField(help_text="Main title on the card, e.g. 'Early Childhood Foundation'", max_length=200)),
                ('description', models.TextField(help_text='Short paragraph about this stage')),
                ('feature_1', models.CharField(blank=True, max_length=200)),
                ('feature_2', models.CharField(blank=True, max_length=200)),
                ('feature_3', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Curriculum Stage',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='menu',
            name='page',
            field=models.CharField(blank=True, choices=[('layout_1', 'Layout 1 — Image with Description'), ('layout_2', 'Layout 2 — Photo Grid'), ('layout_3', 'Layout 3 — Rich Text'), ('contact', 'Contact'), ('faculty_junior', 'Faculty — Junior School'), ('faculty_middle', 'Faculty — Middle School'), ('faculty_senior', 'Faculty — Senior School'), ('gallery', 'Gallery'), ('events', 'Events'), ('notices', 'Notices'), ('students', 'Students'), ('results', 'Results'), ('admission_results', 'Admission Results'), ('facilities_list', 'Facilities — dropdown from Facility model'), ('curriculum_list', 'Curriculum — dropdown from Curriculum Stages')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='page',
            field=models.CharField(choices=[('layout_1', 'Layout 1 — Image with Description'), ('layout_2', 'Layout 2 — Photo Grid'), ('layout_3', 'Layout 3 — Rich Text'), ('contact', 'Contact'), ('faculty_junior', 'Faculty — Junior School'), ('faculty_middle', 'Faculty — Middle School'), ('faculty_senior', 'Faculty — Senior School'), ('gallery', 'Gallery'), ('events', 'Events'), ('notices', 'Notices'), ('students', 'Students'), ('results', 'Results'), ('admission_results', 'Admission Results'), ('facilities_list', 'Facilities — dropdown from Facility model'), ('curriculum_list', 'Curriculum — dropdown from Curriculum Stages')], max_length=30),
        ),
    ]
