# Generated by Django 5.2.8 on 2026-06-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_curriculumstage_alter_menu_page_alter_submenu_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='logo',
            field=models.ImageField(blank=True, help_text='School logo — shown in the navbar and footer. Upload to replace the default static logo.', null=True, upload_to='site/'),
        ),
    ]
