# Generated by Django 5.2.14 on 2026-06-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_add_direct_menu_to_page_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagephoto',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='pagerichtext',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='pagesection',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='menu',
            name='page',
            field=models.CharField(blank=True, choices=[('layout_1', 'Layout 1 — Image with Description'), ('layout_2', 'Layout 2 — Photo Grid'), ('layout_3', 'Layout 3 — Rich Text')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='page',
            field=models.CharField(choices=[('layout_1', 'Layout 1 — Image with Description'), ('layout_2', 'Layout 2 — Photo Grid'), ('layout_3', 'Layout 3 — Rich Text')], max_length=30),
        ),
    ]
